In [1]:
import pandas as pd
import streamlit as st

In [2]:
### Fuções para tratar telefone: 
appointments_df = pd.read_excel("C:/Users/novo1/OneDrive/Desktop/Dev/Indique_Multiplique-1/Bases/agendamentos_colab-bi_2025-08-14 (1).xlsx")

# Collumns to use
appointments_df_columns = ['ID agendamento', 'ID cliente','Email','Telefone',
                           'Unidade do agendamento', 'Procedimento', 'Data', 'Status']

appointments_df = appointments_df[appointments_df_columns]

branches_to_consider = ['TUCURUVI', 'SANTOS', 'LAPA', 'IPIRANGA', 'COPACABANA',
                            'CAMPINAS','JARDINS', 'SOROCABA','TIJUCA','SANTO AMARO',
                            'ITAIM', 'LONDRINA', 'MOEMA','TATUAPÉ', 'MOOCA','OSASCO',
                            'ALPHAVILLE','SÃO BERNARDO', 'VILA MASCOTE', 'GUARULHOS']

appointments_df = appointments_df.loc[appointments_df['Unidade do agendamento'].isin(branches_to_consider)]

# Treating the date values
appointments_df['Data'] = pd.to_datetime(appointments_df['Data'], format='%d/%m/%Y')
appointments_df["Mes"] = appointments_df['Data'].dt.month

# Data in pt-Br format
appointments_df['Data'] = appointments_df['Data'].dt.strftime('%d/%m/%Y')

appointments_df = appointments_df.loc[appointments_df["Procedimento"].str.contains("AVALIAÇÃO",case= False)]
appointments_df = appointments_df.loc[appointments_df["Status"] == "Atendido"]

appointments_df_columns = ['ID agendamento', 'Data', 'Mes',
                           'Unidade do agendamento','ID cliente',
                           'Email','Telefone', 'Status']

    # Reordering the columns
appointments_df = appointments_df[appointments_df_columns]

appointments_df['Telefone'] = appointments_df['Telefone'].astype(str)

def split_Telefones(df):
# Crie uma nova lista para armazenar as novas linhas
    new_rows = []

    for _, row in df.iterrows():
        # Verifique se o valor de 'Telefones' não é nulo
        if pd.notna(row['Telefone']):
            Telefoness = row['Telefone'].split(' / ')
            for Telefones in Telefoness:
                # Crie uma nova linha para cada Telefones
                new_row = row.copy()
                new_row['Telefone'] = Telefones
                new_rows.append(new_row)

    return pd.DataFrame(new_rows)

appointments_df = split_Telefones(appointments_df)

appointments_df

,ID agendamento,Data,Mes,Unidade do agendamento,ID cliente,Email,Telefone,Status
1279,3080623,09/08/2025,8,TIJUCA,1049303,titanicola04@gmail.com,21969187317,Atendido
1822,3090343,02/08/2025,8,TATUAPÉ,530383,edja_alves@yahoo.com.br,11995094669,Atendido
2062,3093016,01/08/2025,8,TIJUCA,1050821,nutricionistameirylane@gmail.com,21986541777,Atendido
2247,3095027,08/08/2025,8,SOROCABA,1051251,Malagrinewania@gmail.com,15996946877,Atendido
2359,3095983,01/08/2025,8,VILA MASCOTE,1051383,dossadogueto@gmail.com,11969194212,Atendido
...,...,...,...,...,...,...,...,...
21086,3138698,14/08/2025,8,TIJUCA,1057152,ANGELAMCOUTINHO@GMAIL.COM,21997128684,Atendido
21093,3138717,14/08/2025,8,TIJUCA,1057066,vaaaaaipassar@gmail.com,21989477344,Atendido
21119,3138753,14/08/2025,8,OSASCO,1057200,carlosalbeto@hotmail.com,11988488703,Atendido
21161,3138859,14/08/2025,8,SÃO BERNARDO,1057207,erislandia46@gmail.com,11948700541,Atendido
21163,3138864,14/08/2025,8,SÃO BERNARDO,1057213,santosneide@gmail.com,11987362797,Atendido

In [3]:
# Carregar o arquivo Excel
xls = pd.ExcelFile('C:/Users/novo1/OneDrive/Desktop/Dev/Indique_Multiplique-1/Bases/compartilhamentos_20250815110831.xlsx')

# Lista para guardar os dataframes de cada aba
dfs = []

# Iterar por cada aba
for sheet_name in xls.sheet_names:
    # Ler a aba
    df = pd.read_excel(xls, sheet_name=sheet_name)
    # Selecionar colunas específicas
    # Adicionar coluna 'Unidade' com o nome da aba
    df['Unidade'] = sheet_name
    df['Unidade'] = df['Unidade'].str.upper()
    # Append ao lista
    dfs.append(df)

# Concatenar todos os dataframes
indique_df = pd.concat(dfs, ignore_index=True)

indique_df

,ID,Compartilhador,Email compartilhador,Telefone compartilhador,Consultor,Campanha,Criado em,Rede,Leads Gerados,Unidade
0,1866,Emanuele Pereira de Souza,emanuele.agricart@hotmail.com,21969259264,Larissa Rodrigues,Tem alguém especial? Indique para a Pró-Corpo ...,14/08/2025 19:49:41,WhatsApp,0,ALPHAVILLE
1,1858,Geisiane Teixeira,geisi_g@hotmail.com,11946642208,Sabrina Oliveira Dias Sousa,Tem alguém especial? Indique para a Pró-Corpo ...,12/08/2025 17:16:48,WhatsApp,2,ALPHAVILLE
2,1853,Paloma Leão Sousa Pirutti,palomasousa@gmail.com,11949726004,Sabrina Oliveira Dias Sousa,Tem alguém especial? Indique para a Pró-Corpo ...,11/08/2025 20:17:21,WhatsApp,1,ALPHAVILLE
3,1852,Fábio Pereira dos Santos,nunes05pereira05@gmail.com,11992906946,Larissa Rodrigues,Tem alguém especial? Indique para a Pró-Corpo ...,11/08/2025 18:10:04,WhatsApp,4,ALPHAVILLE
4,1851,Denise Pinheiro,Denise.braga21@hotmail.com,11971385767,Larissa Rodrigues,Tem alguém especial? Indique para a Pró-Corpo ...,11/08/2025 16:51:46,WhatsApp,5,ALPHAVILLE
...,...,...,...,...,...,...,...,...,...,...
351,333,Rafael,Rafaelsouza900@gmail.com,11937738232,Sarah leal oliveira,Vamos editar a campanha Tem alguém especial? I...,09/08/2025 09:32:39,WhatsApp,0,VILA MASCOTE
352,332,Marcelo,Marcelo.esnac@gmail.com,11985335615,Sarah leal oliveira,Vamos editar a campanha Tem alguém especial? I...,08/08/2025 11:59:38,WhatsApp,0,VILA MASCOTE
353,330,Thaila Abdalla Guimarães,thaila_2711@hotmail.com,11993549065,Sarah leal oliveira,Vamos editar a campanha Tem alguém especial? I...,07/08/2025 15:06:26,WhatsApp,1,VILA MASCOTE
354,327,LIVIA ALVES DA SILVA,ladsilva88@gmail.com,11978711919,Beatriz Nogueira de Oliveira,Vamos editar a campanha Tem alguém especial? I...,06/08/2025 15:09:46,WhatsApp,0,VILA MASCOTE
355,326,Juliana Cristina Pelin,juliana_davantel@outlook.com,5519997813227,Sarah leal oliveira,Vamos editar a campanha Tem alguém especial? I...,05/08/2025 13:37:58,WhatsApp,0,VILA MASCOTE

In [9]:
indique_appointments_merge_email = pd.merge(indique_df,appointments_df,
                                      left_on='Email compartilhador',
                                      right_on='Email',
                                      how='left')

indique_appointments_merge_telefone = pd.merge(indique_df,appointments_df,
                                      left_on='Telefone compartilhador',
                                      right_on='Telefone',
                                      how='left')

indique_appointments_merge_final = pd.concat([indique_appointments_merge_email,indique_appointments_merge_telefone])

indique_appointments_merge_final = indique_appointments_merge_final.loc[~indique_appointments_merge_final['ID agendamento'].isna()]

indique_appointments_merge_final = indique_appointments_merge_final.drop_duplicates(subset=['ID'])

base_indique_final = indique_appointments_merge_final

base_indique_final_columns = ['ID', 'Compartilhador', 'Email compartilhador',
                            'Telefone compartilhador', 'Consultor','Unidade', 'Criado em',
                            'ID agendamento', 'Data','ID cliente', 'Status','Leads Gerados']

base_indique_final = base_indique_final[base_indique_final_columns]


## Aguardando confirmação da Pat se consider ou não.
# duplicados = base_indique_final.loc[base_indique_final['ID agendamento'].duplicated(keep=False)]

# duplicados = duplicados.sort_values(by=['ID agendamento'])

# duplicados

indique_gp = base_indique_final.groupby(["Consultor",'Unidade']).agg({'Leads Gerados' : 'sum'}).reset_index()

indique_gp = indique_gp.sort_values(by=['Leads Gerados'],ascending=False)

# indique_gp = indique_gp.loc[indique_gp['Leads Gerados'] != 0]

indique_gp

                             Consultor       Unidade Leads Gerados
6                         Debora Souza      LONDRINA            41
14                   Larissa Rodrigues    ALPHAVILLE            37
7               Fernanda Machado Leite        TIJUCA            18
19         Sabrina Oliveira Dias Sousa    ALPHAVILLE            18
10      Ingrid Caroline Santos Andrade      CAMPINAS            11
5               Camilly Giselle Barros        OSASCO            10
22               Vitoria Almeida Silva        OSASCO             5
23                        Yasmin Ramos  SÃO BERNARDO             4
13             Karisa da Silva Pereira         MOOCA             4
1             Aline Araujo de Oliveira     GUARULHOS             4
3                Barbara Sumire Ireijo        SANTOS             3
8             Gabrielly Novaes de Melo          LAPA             3
20                 Sarah leal oliveira  VILA MASCOTE             2
0                  Alany Melo de Souza        SANTOS             2
11  Isabelle pellegrini de Albuquerque   SANTO AMARO             1
16              Meire catonho da Silva  VILA MASCOTE             1
18                       Nicolly Alves          LAPA             1
9          Giulia Galache Saraiva Dias       JARDINS             1
15            Laysla Ferreira de Jesus     GUARULHOS             0
17   Natalia Aparecida Zanoni da Silva          LAPA             0
4        Beatriz Nogueira de  Oliveira  VILA MASCOTE             0
21               Thamyres Lima Marques        TIJUCA             0
2                Amanda Raquel Cassula      LONDRINA             0
12            Jihad Pereira dos Santos      IPIRANGA             0

In [11]:
indique_gp.to_excel("C:/Users/novo1/OneDrive/Desktop/Dev/Indique_Multiplique-1/Bases/Indique_&_multiplique_até_14-08.xlsx")